table customers
	lineageTag: 04e395a7-862f-4faa-8b61-167f02bb86a4

	measure customer_avg_age = AVERAGE(customers[customer_age])
		lineageTag: 6322e86e-0419-415b-a7b2-79817c15d504

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: ee72bfd5-7494-4eae-b25a-c510775d1901
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_name
		dataType: string
		lineageTag: aeafc106-96b2-415b-aa15-6d0ba9cf879c
		summarizeBy: none
		sourceColumn: customer_name

		annotation SummarizationSetBy = Automatic

	column customer_payment_type
		dataType: string
		lineageTag: a9524414-46c3-406e-a963-f7504050fdda
		summarizeBy: none
		sourceColumn: customer_payment_type

		annotation SummarizationSetBy = Automatic

	column customer_age
		dataType: int64
		formatString: 0
		lineageTag: 1e62cacf-f613-492f-88eb-df2fa86a8cac
		summarizeBy: sum
		sourceColumn: customer_age

		annotation SummarizationSetBy = Automatic

	column customer_region
		dataType: string
		lineageTag: bf47d717-fd84-431b-a8c6-50818139af4d
		summarizeBy: none
		sourceColumn: customer_region

		annotation SummarizationSetBy = Automatic

	column customer_signup_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8a92194e-0612-45e7-bd95-0e278ecbf740
		summarizeBy: none
		sourceColumn: customer_signup_date

		variation Variation
			isDefault
			relationship: 2ac88379-40e9-4a36-92de-047e9f4e0310
			defaultHierarchy: LocalDateTable_a3cf9bad-64c0-4f53-b152-a17a840276f1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition customers = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\hayia\projects\boot-dev\dataviz-project\customers.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", Int64.Type}, {"customer_name", type text}, {"customer_payment_type", type text}, {"customer_age", Int64.Type}, {"customer_region", type text}, {"customer_signup_date", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

