table sales
	lineageTag: bd96d601-9929-47f2-aaf4-e2c1c9ffcd99

	measure total_revenue = SUM(sales[discounted_price])
		lineageTag: d4d33997-f7d5-4c9d-ad20-ab1b5cb6e9b0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure total_units_sold = SUM(sales[sale_quantity])
		formatString: 0
		lineageTag: ec673b52-0809-4655-a894-654e00654961

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: ea9a0225-b11e-44a9-bf06-fd676efc7c61
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date_id
		dataType: int64
		formatString: 0
		lineageTag: e53c872b-bbca-4981-87e3-c5cfcafeddca
		summarizeBy: none
		sourceColumn: date_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: 4502e303-b275-4c52-82b2-88f7fdaf081b
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: 86631219-7096-4145-86df-9fcb7ad1136a
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column store_id
		dataType: int64
		formatString: 0
		lineageTag: 0736dbe2-3dca-4a26-9c2e-5cd81204e80d
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = Automatic

	column sale_quantity
		dataType: int64
		formatString: 0
		lineageTag: 9663ac50-dc53-4df6-bd5d-f1f9911fe257
		summarizeBy: sum
		sourceColumn: sale_quantity

		annotation SummarizationSetBy = Automatic

	column sale_discount
		dataType: double
		isHidden
		lineageTag: 0a5093e6-58be-4f83-b433-a055b45f7ea0
		summarizeBy: sum
		sourceColumn: sale_discount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column price = sales[sale_quantity] * RELATED(products[product_list_price])
		lineageTag: ab58eff6-d5f6-458c-8731-64e3f26a46e1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column discounted_price = sales[price]*(1-sales[sale_discount])
		lineageTag: 93185aec-9b78-4e73-adf9-2ba649062ec7
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column bulk_order = if(sales[sale_quantity]>3, TRUE(),FALSE())
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c6ad4a4c-986e-42f7-938e-099cc6889240
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\hayia\projects\boot-dev\dataviz-project\sales.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date_id", Int64.Type}, {"customer_id", Int64.Type}, {"product_id", Int64.Type}, {"store_id", Int64.Type}, {"sale_quantity", Int64.Type}, {"sale_discount", type number}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"sale_id"})
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

